version: '3.9'

services:
  db:
    image: docker.io/postgres:14.2-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 15432:5432

volumes:
  postgres-data:
